### ISSUE TITLE
8.4 - poprawki

### ISSUE THREAD

**Issue by michal-bootcamp** [zuzannababis/project-pizzeria#1]
1. katalog `node_modules` nie powinien znaleźć się na githubie
2. zamiast wpisywać nazwę klasy, użyj właściwości obiektu `classNames`, gdzie odpowiednią klasę sobie zapisaliśmy
https://github.com/zuzannababis/project-pizzeria/blob/f32e41c2e3b1d992d7223eaea97a6999934921b7/src/js/script.js#L113

**Comment by zuzannababis** [comment]
2. zrobione
1. nie jestem pewna czy wszystko poszło dobrze :p zrobiłam wg Twojej instrukcji (usunelam pliki, zrobilam commit) ale po wpisywaniu komendy git rm -r --cached node_modules wyskakiwało mi za kazdym razem fatal: pathspec 'node_modules' did not match any files. Tak wiec dziś juz raczej nie dam rady tego ogarnąć, zajmę się tym za 2 tygodnie :)
